server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      type: simple
      simple:
        acknowledge-mode: manual #手动确认
        prefetch: 5 #限制每次发送一条数据。
        concurrency: 10 #同一个队列启动几个消费者
        max-concurrency: 20 #启动消费者最大数量
        batch-size: 10
        consumers-per-queue: 1 # direct模式用

        #重试策略相关配置
        retry:
          enabled: true #是否支持重试
          max-attempts: 5
          stateless: false
          #时间策略乘数因子
          multiplier: 1.0
          initial-interval: 1000ms
          max-interval: 10000ms
        default-requeue-rejected: true


queue:
  test:
    name: rabbit.test.queue
    dlx:
      exchange: dlx.exchange
      routeKey: dlx.route
    dlq:
      queue: dlq.queue




